package org.jetbrains.kotlinx.dataframe.examples.titanic.ml

import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.cast
import org.jetbrains.kotlinx.dataframe.api.convertTo
import org.jetbrains.kotlinx.dataframe.api.generateInterfaces
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.io.readCsv

/**
 * This data schema is generated by reading the CSV once.
 * We then call [generateInterfaces] on its schema to generate the Kotlin interface.
 *
 * Afterward, we can relatively safely [cast] or [convertTo] any search call to [Passenger] and
 * the compiler plugin can handle the rest.
 */
fun main() {
    DataFrame.readCsv(
        url = object {}::class.java.getResource("/titanic.csv")!!,
        delimiter = ';',
    ).generateInterfaces("Passenger").print()
}

@DataSchema
interface Passenger {
    val age: Double?
    val boat: String?
    val body: Int?
    val cabin: String?
    val embarked: String?
    val fare: Double?
    val homedest: String?
    val name: String
    val parch: Int?
    val pclass: Int
    val sex: String?
    val sibsp: Int?
    val survived: Int
    val ticket: String
}
