package org.jetbrains.kotlinx.dataframe.examples.titanic.ml

import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.cast
import org.jetbrains.kotlinx.dataframe.api.convertTo
import org.jetbrains.kotlinx.dataframe.api.generateInterfaces
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.io.readCsv

/**
 * This data schema is generated by reading the CSV once.
 * We then call [generateInterfaces] on its schema to generate the Kotlin interface.
 *
 * Afterward, we can safely [cast] or [convertTo] any 'titanic.csv' DataFrame to [Passenger] and
 * the compiler plugin can handle the rest.
 *
 * Since, in this example, we're working with a single file, the generated data schema will always accurately represent
 * the data read from the CSV. This may not always be the case, like when you're building a pipeline that can
 * have varying data coming through (like unexpected nulls),
 * in which case you'll have to manually modify the data schema interface, or use a more 'complete' sample to generate
 * the interface from.
 *
 * Data schemas are allowed to have only a subset of the columns present in the actual dataframe.
 * Additional columns (like if the csv had an additional `address` column, for instance) can be preserved or dropped
 * when casting or converting to [Passenger].
 *
 * For more information, see [the website](https://kotlin.github.io/dataframe/dataschema.html).
 */
fun main() {
    DataFrame.readCsv(
        url = object {}::class.java.getResource("/titanic.csv")!!,
        delimiter = ';',
    ).generateInterfaces("Passenger").print()
}

@DataSchema
interface Passenger {
    val age: Double?
    val boat: String?
    val body: Int?
    val cabin: String?
    val embarked: String?
    val fare: Double?
    val homedest: String?
    val name: String
    val parch: Int?
    val pclass: Int
    val sex: String?
    val sibsp: Int?
    val survived: Int
    val ticket: String
}
