@file:Suppress("UNCHECKED_CAST", "USELESS_CAST")
package org.jetbrains.kotlinx.dataframe.io
import org.jetbrains.kotlinx.dataframe.annotations.*
import org.jetbrains.kotlinx.dataframe.ColumnsScope
import org.jetbrains.kotlinx.dataframe.DataColumn
import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.DataRow
import org.jetbrains.kotlinx.dataframe.columns.ColumnGroup

val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.default: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4> @JvmName("DataFrameType3_default") get() = this["default"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.default: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4> @JvmName("DataFrameType3_default") get() = this["default"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.default: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4?> @JvmName("NullableDataFrameType3_default") get() = this["default"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4?>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.default: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4?> @JvmName("NullableDataFrameType3_default") get() = this["default"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType4?>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.high: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6> @JvmName("DataFrameType3_high") get() = this["high"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.high: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6> @JvmName("DataFrameType3_high") get() = this["high"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.high: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6?> @JvmName("NullableDataFrameType3_high") get() = this["high"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6?>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.high: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6?> @JvmName("NullableDataFrameType3_high") get() = this["high"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType6?>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.maxres: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8> @JvmName("DataFrameType3_maxres") get() = this["maxres"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.maxres: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8> @JvmName("DataFrameType3_maxres") get() = this["maxres"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.maxres: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8?> @JvmName("NullableDataFrameType3_maxres") get() = this["maxres"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8?>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.maxres: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8?> @JvmName("NullableDataFrameType3_maxres") get() = this["maxres"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType8?>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.medium: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5> @JvmName("DataFrameType3_medium") get() = this["medium"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.medium: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5> @JvmName("DataFrameType3_medium") get() = this["medium"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.medium: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5?> @JvmName("NullableDataFrameType3_medium") get() = this["medium"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5?>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.medium: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5?> @JvmName("NullableDataFrameType3_medium") get() = this["medium"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType5?>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.standard: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7> @JvmName("DataFrameType3_standard") get() = this["standard"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3>.standard: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7> @JvmName("DataFrameType3_standard") get() = this["standard"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7>
val ColumnsScope<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.standard: ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7?> @JvmName("NullableDataFrameType3_standard") get() = this["standard"] as ColumnGroup<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7?>
val DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType3?>.standard: DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7?> @JvmName("NullableDataFrameType3_standard") get() = this["standard"] as DataRow<org.jetbrains.kotlinx.dataframe.io.PlaylistJsonTest.DataFrameType7?>
