package org.jetbrains.kotlinx.dataframe.examples.youtube

import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.cast
import org.jetbrains.kotlinx.dataframe.api.convertTo
import org.jetbrains.kotlinx.dataframe.api.generateInterfaces
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.api.schema

/**
 * These data schemas are generated by calling the YouTube API search once.
 * We then call [generateInterfaces] on its schema to generate the Kotlin interfaces.
 *
 * Afterward, we can relatively safely [cast] or [convertTo] any search call to [StatisticsResponse] and
 * the compiler plugin can handle the rest.
 */
fun main() {
    val id = "uHKfrz65KSU"
    val df = load("videos?part=statistics&id=$id")
    df.schema()
        .generateInterfaces("StatisticsResponse")
        .print()
}

@DataSchema(isOpen = false)
interface StatisticsResponse2 {
    val commentCount: String
    val favoriteCount: String
    val likeCount: String
    val viewCount: String
}

@DataSchema(isOpen = false)
interface StatisticsResponse1 {
    val etag: String
    val id: String
    val kind: String
    val statistics: StatisticsResponse2
}

@DataSchema(isOpen = false)
interface StatisticsResponse3 {
    val resultsPerPage: Int
    val totalResults: Int
}

@DataSchema
interface StatisticsResponse {
    val etag: String
    val items: List<StatisticsResponse1>
    val kind: String
    val pageInfo: StatisticsResponse3
}
