[versions]
# Sync manually with module.yaml!
kotlin = "2.4.20"
dataframe = "1.0.0-dev"
kandy = "0.8.5"
ktlint = "1.8.0"
exec = "3.6.4"

[libraries]
dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }
kandy = { module = "org.jetbrains.kotlinx:kandy-lets-plot", version.ref = "kandy" }
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
exec = { group = "org.codehaus.mojo", name = "exec-maven-plugin", version.ref = "exec" }

[plugins]

# The Kotlin DataFrame Compiler plugin is the same version as the Kotlin plugin.
kotlin-dataframe = { id = "org.jetbrains.kotlin.plugin.dataframe", version.ref = "kotlin" }
