package org.jetbrains.kotlinx.dataframe.examples.json.openApi

import kotlinx.datetime.LocalDateTime
import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.ConvertSchemaDsl
import org.jetbrains.kotlinx.dataframe.api.DataSchemaEnum
import org.jetbrains.kotlinx.dataframe.api.JsonPath
import org.jetbrains.kotlinx.dataframe.api.convertTo
import org.jetbrains.kotlinx.dataframe.io.JSON.TypeClashTactic.ANY_COLUMNS
import org.jetbrains.kotlinx.dataframe.io.convertDataRowsWithOpenApi
import org.jetbrains.kotlinx.dataframe.io.readJson
import org.jetbrains.kotlinx.dataframe.io.readJsonStr
import org.jetbrains.kotlinx.dataframe.io.readOpenApi
import java.io.InputStream
import java.net.URL

/**
 * Here we generate the [OnePassword] [DataSchema] interface using the 1Password OpenAPI specification.
 * This will be used in the `onePassword.kt` file where we parse a JSON result from that API.
 *
 * Visit our [documentation](https://kotlin.github.io/dataframe/openapi.html) to learn more about
 * which modules you need to include in your project and how to use them.
 */
fun main() {
    val onePasswordSpec =
        "https://raw.githubusercontent.com/1Password/connect/aac5e44b27570036e6b56e9f5b2a398a824ae5fc/docs/openapi/spec.yaml"

    val dataSchemaCode = readOpenApi(
        uri = onePasswordSpec,
        name = "OnePassword",
        extensionProperties = false,
        auth = null,
        options = null,
        generateHelperCompanionObject = false,
    )

    println(dataSchemaCode)
}

// auto-generated by main()
@Suppress("PropertyName")
interface OnePassword {

    @DataSchema(isOpen = false)
    interface ErrorResponse {
        val status: Int?
        val message: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToErrorResponse(
                convertTo: ConvertSchemaDsl<ErrorResponse>.() -> Unit = {
                },
            ): DataFrame<ErrorResponse> =
                convertTo<ErrorResponse> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<ErrorResponse> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToErrorResponse()

            fun readJson(path: String): DataFrame<ErrorResponse> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToErrorResponse()

            fun readJson(stream: InputStream): DataFrame<ErrorResponse> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToErrorResponse()

            fun readJsonStr(text: String): DataFrame<ErrorResponse> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToErrorResponse()
        }
    }

    @DataSchema(isOpen = false)
    interface File {
        val id: String?
        val name: String?
        val size: Int?
        val content_path: String?
        val section: Section?
        val content: Byte?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToFile(convertTo: ConvertSchemaDsl<File>.() -> Unit = {}): DataFrame<File> =
                convertTo<File> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<File> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFile()

            fun readJson(path: String): DataFrame<File> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFile()

            fun readJson(stream: InputStream): DataFrame<File> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFile()

            fun readJsonStr(text: String): DataFrame<File> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFile()
        }
    }

    @DataSchema(isOpen = false)
    interface Section {
        val id: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToSection(
                convertTo: ConvertSchemaDsl<Section>.() -> Unit = {
                },
            ): DataFrame<Section> =
                convertTo<Section> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Section> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection()

            fun readJson(path: String): DataFrame<Section> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection()

            fun readJson(stream: InputStream): DataFrame<Section> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection()

            fun readJsonStr(text: String): DataFrame<Section> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection()
        }
    }

    @DataSchema(isOpen = false)
    interface Vault {
        val id: String?
        val name: String?
        val description: String?
        val attributeVersion: Int?
        val contentVersion: Int?
        val items: Int?
        val type: Type?
        val createdAt: LocalDateTime?
        val updatedAt: LocalDateTime?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToVault(convertTo: ConvertSchemaDsl<Vault>.() -> Unit = {}): DataFrame<Vault> =
                convertTo<Vault> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Vault> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault()

            fun readJson(path: String): DataFrame<Vault> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault()

            fun readJson(stream: InputStream): DataFrame<Vault> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault()

            fun readJsonStr(text: String): DataFrame<Vault> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault()
        }
    }

    enum class Type(override val value: String) : DataSchemaEnum {
        USER_CREATED("USER_CREATED"),
        PERSONAL("PERSONAL"),
        EVERYONE("EVERYONE"),
        TRANSFER("TRANSFER"),
    }

    @DataSchema(isOpen = false)
    interface GeneratorRecipe {
        val length: Int?
        val characterSets: List<CharacterSets>?
        val excludeCharacters: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToGeneratorRecipe(
                convertTo: ConvertSchemaDsl<GeneratorRecipe>.() -> Unit = {
                },
            ): DataFrame<GeneratorRecipe> =
                convertTo<GeneratorRecipe> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<GeneratorRecipe> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToGeneratorRecipe()

            fun readJson(path: String): DataFrame<GeneratorRecipe> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToGeneratorRecipe()

            fun readJson(stream: InputStream): DataFrame<GeneratorRecipe> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToGeneratorRecipe()

            fun readJsonStr(text: String): DataFrame<GeneratorRecipe> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToGeneratorRecipe()
        }
    }

    enum class CharacterSets(override val value: String) : DataSchemaEnum {
        LETTERS("LETTERS"),
        DIGITS("DIGITS"),
        SYMBOLS("SYMBOLS"),
    }

    @DataSchema(isOpen = false)
    interface Item {
        val id: String?
        val title: String?
        val vault: Vault1
        val category: Category
        val urls: DataFrame<UrlsContent?>
        val favorite: Boolean?
        val tags: List<String>?
        val version: Int?
        val state: State?
        val createdAt: LocalDateTime?
        val updatedAt: LocalDateTime?
        val lastEditedBy: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToItem(convertTo: ConvertSchemaDsl<Item>.() -> Unit = {}): DataFrame<Item> =
                convertTo<Item> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Item> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem()

            fun readJson(path: String): DataFrame<Item> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem()

            fun readJson(stream: InputStream): DataFrame<Item> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem()

            fun readJsonStr(text: String): DataFrame<Item> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem()
        }
    }

    @DataSchema(isOpen = false)
    interface Vault1 {
        val id: String

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToVault1(convertTo: ConvertSchemaDsl<Vault1>.() -> Unit = {}): DataFrame<Vault1> =
                convertTo<Vault1> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Vault1> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault1()

            fun readJson(path: String): DataFrame<Vault1> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault1()

            fun readJson(stream: InputStream): DataFrame<Vault1> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault1()

            fun readJsonStr(text: String): DataFrame<Vault1> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault1()
        }
    }

    enum class Category(override val value: String) : DataSchemaEnum {
        LOGIN("LOGIN"),
        PASSWORD("PASSWORD"),
        API_CREDENTIAL("API_CREDENTIAL"),
        SERVER("SERVER"),
        DATABASE("DATABASE"),
        CREDIT_CARD("CREDIT_CARD"),
        MEMBERSHIP("MEMBERSHIP"),
        PASSPORT("PASSPORT"),
        SOFTWARE_LICENSE("SOFTWARE_LICENSE"),
        OUTDOOR_LICENSE("OUTDOOR_LICENSE"),
        SECURE_NOTE("SECURE_NOTE"),
        WIRELESS_ROUTER("WIRELESS_ROUTER"),
        BANK_ACCOUNT("BANK_ACCOUNT"),
        DRIVER_LICENSE("DRIVER_LICENSE"),
        IDENTITY("IDENTITY"),
        REWARD_PROGRAM("REWARD_PROGRAM"),
        DOCUMENT("DOCUMENT"),
        EMAIL_ACCOUNT("EMAIL_ACCOUNT"),
        SOCIAL_SECURITY_NUMBER("SOCIAL_SECURITY_NUMBER"),
        MEDICAL_RECORD("MEDICAL_RECORD"),
        SSH_KEY("SSH_KEY"),
        CUSTOM("CUSTOM"),
    }

    @DataSchema(isOpen = false)
    interface UrlsContent {
        val label: String?
        val primary: Boolean?
        val href: String

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToUrlsContent(
                convertTo: ConvertSchemaDsl<UrlsContent>.() -> Unit = {
                },
            ): DataFrame<UrlsContent> =
                convertTo<UrlsContent> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<UrlsContent> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToUrlsContent()

            fun readJson(path: String): DataFrame<UrlsContent> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToUrlsContent()

            fun readJson(stream: InputStream): DataFrame<UrlsContent> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToUrlsContent()

            fun readJsonStr(text: String): DataFrame<UrlsContent> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToUrlsContent()
        }
    }

    enum class State(override val value: String) : DataSchemaEnum {
        ARCHIVED("ARCHIVED"),
        DELETED("DELETED"),
    }

    @DataSchema(isOpen = false)
    interface Field {
        val id: String
        val section: Section1?
        val type: Type1
        val purpose: Purpose?
        val label: String?
        val value: String?
        val generate: Boolean?
        val recipe: GeneratorRecipe?
        val entropy: Float?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToField(convertTo: ConvertSchemaDsl<Field>.() -> Unit = {}): DataFrame<Field> =
                convertTo<Field> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Field> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToField()

            fun readJson(path: String): DataFrame<Field> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToField()

            fun readJson(stream: InputStream): DataFrame<Field> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToField()

            fun readJsonStr(text: String): DataFrame<Field> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToField()
        }
    }

    @DataSchema(isOpen = false)
    interface Section1 {
        val id: String

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToSection1(
                convertTo: ConvertSchemaDsl<Section1>.() -> Unit = {
                },
            ): DataFrame<Section1> =
                convertTo<Section1> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Section1> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection1()

            fun readJson(path: String): DataFrame<Section1> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection1()

            fun readJson(stream: InputStream): DataFrame<Section1> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection1()

            fun readJsonStr(text: String): DataFrame<Section1> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSection1()
        }
    }

    enum class Type1(override val value: String) : DataSchemaEnum {
        STRING("STRING"),
        EMAIL("EMAIL"),
        CONCEALED("CONCEALED"),
        URL("URL"),
        TOTP("TOTP"),
        DATE("DATE"),
        MONTH_YEAR("MONTH_YEAR"),
        MENU("MENU"),
    }

    enum class Purpose(override val value: String) : DataSchemaEnum {
        EMPTY_STRING(""),
        USERNAME("USERNAME"),
        PASSWORD("PASSWORD"),
        NOTES("NOTES"),
    }

    @DataSchema(isOpen = false)
    interface FullItem : Item {
        val sections: DataFrame<SectionsContent?>
        val fields: DataFrame<Field?>
        val files: DataFrame<File?>

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToFullItem(
                convertTo: ConvertSchemaDsl<FullItem>.() -> Unit = {
                },
            ): DataFrame<FullItem> =
                convertTo<FullItem> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<FullItem> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFullItem()

            fun readJson(path: String): DataFrame<FullItem> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFullItem()

            fun readJson(stream: InputStream): DataFrame<FullItem> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFullItem()

            fun readJsonStr(text: String): DataFrame<FullItem> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToFullItem()
        }
    }

    @DataSchema(isOpen = false)
    interface SectionsContent {
        val id: String?
        val label: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToSectionsContent(
                convertTo: ConvertSchemaDsl<SectionsContent>.() -> Unit = {
                },
            ): DataFrame<SectionsContent> =
                convertTo<SectionsContent> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<SectionsContent> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSectionsContent()

            fun readJson(path: String): DataFrame<SectionsContent> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSectionsContent()

            fun readJson(stream: InputStream): DataFrame<SectionsContent> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSectionsContent()

            fun readJsonStr(text: String): DataFrame<SectionsContent> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToSectionsContent()
        }
    }

    @DataSchema(isOpen = false)
    interface APIRequest {
        val requestId: String?
        val timestamp: LocalDateTime?
        val action: Action?
        val result: Result?
        val actor: Actor?
        val resource: Resource?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToAPIRequest(
                convertTo: ConvertSchemaDsl<APIRequest>.() -> Unit = {
                },
            ): DataFrame<APIRequest> =
                convertTo<APIRequest> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<APIRequest> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToAPIRequest()

            fun readJson(path: String): DataFrame<APIRequest> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToAPIRequest()

            fun readJson(stream: InputStream): DataFrame<APIRequest> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToAPIRequest()

            fun readJsonStr(text: String): DataFrame<APIRequest> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToAPIRequest()
        }
    }

    enum class Action(override val value: String) : DataSchemaEnum {
        READ("READ"),
        CREATE("CREATE"),
        UPDATE("UPDATE"),
        DELETE("DELETE"),
    }

    enum class Result(override val value: String) : DataSchemaEnum {
        SUCCESS("SUCCESS"),
        DENY("DENY"),
    }

    @DataSchema(isOpen = false)
    interface Actor {
        val id: String?
        val account: String?
        val jti: String?
        val userAgent: String?
        val requestIp: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToActor(convertTo: ConvertSchemaDsl<Actor>.() -> Unit = {}): DataFrame<Actor> =
                convertTo<Actor> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Actor> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToActor()

            fun readJson(path: String): DataFrame<Actor> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToActor()

            fun readJson(stream: InputStream): DataFrame<Actor> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToActor()

            fun readJsonStr(text: String): DataFrame<Actor> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToActor()
        }
    }

    enum class Type2(override val value: String) : DataSchemaEnum {
        ITEM("ITEM"),
        VAULT("VAULT"),
    }

    @DataSchema(isOpen = false)
    interface Vault2 {
        val id: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToVault2(convertTo: ConvertSchemaDsl<Vault2>.() -> Unit = {}): DataFrame<Vault2> =
                convertTo<Vault2> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Vault2> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault2()

            fun readJson(path: String): DataFrame<Vault2> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault2()

            fun readJson(stream: InputStream): DataFrame<Vault2> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault2()

            fun readJsonStr(text: String): DataFrame<Vault2> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToVault2()
        }
    }

    @DataSchema(isOpen = false)
    interface Item1 {
        val id: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToItem1(convertTo: ConvertSchemaDsl<Item1>.() -> Unit = {}): DataFrame<Item1> =
                convertTo<Item1> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Item1> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem1()

            fun readJson(path: String): DataFrame<Item1> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem1()

            fun readJson(stream: InputStream): DataFrame<Item1> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem1()

            fun readJsonStr(text: String): DataFrame<Item1> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToItem1()
        }
    }

    @DataSchema(isOpen = false)
    interface Resource {
        val type: Type2?
        val vault: Vault2?
        val item: Item1?
        val itemVersion: Int?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToResource(
                convertTo: ConvertSchemaDsl<Resource>.() -> Unit = {
                },
            ): DataFrame<Resource> =
                convertTo<Resource> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Resource> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToResource()

            fun readJson(path: String): DataFrame<Resource> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToResource()

            fun readJson(stream: InputStream): DataFrame<Resource> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToResource()

            fun readJsonStr(text: String): DataFrame<Resource> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToResource()
        }
    }

    enum class Op(override val value: String) : DataSchemaEnum {
        ADD("add"),
        REMOVE("remove"),
        REPLACE("replace"),
    }

    @DataSchema(isOpen = false)
    interface Value {
        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToValue(convertTo: ConvertSchemaDsl<Value>.() -> Unit = {}): DataFrame<Value> =
                convertTo<Value> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<Value> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToValue()

            fun readJson(path: String): DataFrame<Value> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToValue()

            fun readJson(stream: InputStream): DataFrame<Value> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToValue()

            fun readJsonStr(text: String): DataFrame<Value> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToValue()
        }
    }

    @DataSchema(isOpen = false)
    interface PatchContent {
        val op: Op
        val path: String
        val value: Value?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToPatchContent(
                convertTo: ConvertSchemaDsl<PatchContent>.() -> Unit = {
                },
            ): DataFrame<PatchContent> =
                convertTo<PatchContent> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<PatchContent> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToPatchContent()

            fun readJson(path: String): DataFrame<PatchContent> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToPatchContent()

            fun readJson(stream: InputStream): DataFrame<PatchContent> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToPatchContent()

            fun readJsonStr(text: String): DataFrame<PatchContent> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToPatchContent()
        }
    }

    @DataSchema(isOpen = false)
    interface ServiceDependency {
        val service: String?
        val status: String?
        val message: String?

        companion object {
            val keyValuePaths: List<JsonPath>
                get() = listOf()

            fun DataFrame<*>.convertToServiceDependency(
                convertTo: ConvertSchemaDsl<ServiceDependency>.() -> Unit = {
                },
            ): DataFrame<ServiceDependency> =
                convertTo<ServiceDependency> {
                    convertDataRowsWithOpenApi()
                    convertTo()
                }

            fun readJson(url: URL): DataFrame<ServiceDependency> =
                DataFrame
                    .readJson(url, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToServiceDependency()

            fun readJson(path: String): DataFrame<ServiceDependency> =
                DataFrame
                    .readJson(path, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToServiceDependency()

            fun readJson(stream: InputStream): DataFrame<ServiceDependency> =
                DataFrame
                    .readJson(stream, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToServiceDependency()

            fun readJsonStr(text: String): DataFrame<ServiceDependency> =
                DataFrame
                    .readJsonStr(text, typeClashTactic = ANY_COLUMNS, keyValuePaths = keyValuePaths)
                    .convertToServiceDependency()
        }
    }
}
typealias Patch = DataFrame<OnePassword.PatchContent>
