package org.jetbrains.kotlinx.dataframe.api

import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.annotations.ColumnName
import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.columns.ColumnGroup
import org.jetbrains.kotlinx.dataframe.columns.FrameColumn
import org.jetbrains.kotlinx.dataframe.documentation.DocumentationUrls
import org.jetbrains.kotlinx.dataframe.documentation.ExcludeFromSources
import org.jetbrains.kotlinx.dataframe.impl.api.toSequenceImpl
import kotlin.reflect.typeOf

/**
 * The {@get [CommonToListDocs.RESULT]} has one [T\] instance per row, in the order of the rows.
 *
 * [T\] has to be a data class. An interface does not work, even one marked with [DataSchema].
 * A generic data class works too, for example, `Pair<String, Int>`.
 * Each instance is created by the primary constructor of [T\].
 * Each constructor parameter gets the value of the column with the same name,
 * or with the name given in [ColumnName]. Names are case-sensitive.
 * The order of the columns does not matter, and columns that match no parameter are ignored.
 * A parameter with a default value gets this value when there is no column for it.
 *
 * When a column type differs from the parameter type, the values are converted
 * the same way as in [convertTo][DataFrame.convertTo], for example, from [Int] to [Long].
 * A [ColumnGroup] becomes a nested data class,
 * and a [FrameColumn] becomes a [List] of data class instances, or a [DataFrame].
 * A frame that goes into a `DataFrame<S>` parameter is converted to the schema of `S`
 * the same way as in [convertTo][DataFrame.convertTo], and its other columns stay.
 * A frame that goes into a `DataFrame<*>` parameter is passed as it is.
 *
 * An exception is thrown when:
 * - [T\] is not a data class;
 * - there is no column for a constructor parameter without a default value;
 * - a column has `null` values, but its parameter is not nullable;
 * - a value cannot be converted to the parameter type;
 * - a frame cannot be converted to the schema of its `DataFrame<S>` parameter,
 *   for example, because a column of `S` is missing.
 *
 * For more information: {@get [CommonToListDocs.URL]}
 *
 * See also:
 *  - [toDataFrame][Iterable.toDataFrame] — the reverse operation: creates a [DataFrame] from a list of objects.
 *  - {@get [CommonToListDocs.SIBLINGS]}
 *  - [convertTo][DataFrame.convertTo] — changes the [DataFrame] to match the schema of [T\]
 *    and returns a [DataFrame] instead.
 */
@ExcludeFromSources
internal interface CommonToListDocs {

    // What the function returns, like "list"
    @ExcludeFromSources
    typealias RESULT = Nothing

    // The sibling functions that return the other collection type (a part of the `See also` list)
    @ExcludeFromSources
    typealias SIBLINGS = Nothing

    // Link to the corresponding page on the documentation website
    @ExcludeFromSources
    typealias URL = Nothing

    // The function that takes the type explicitly, like [toListOf][DataFrame.toListOf]
    @ExcludeFromSources
    typealias OF_FUNCTION = Nothing

    /**
     * Use it only when the type argument of this [DataFrame] is known to be a data class.
     * On a `DataFrame<*>`, such as the result of [dataFrameOf] or of reading a file,
     * this function throws an exception, because there is no data class to create.
     * With the compiler plugin, the same happens even right after
     * [toDataFrame][Iterable.toDataFrame] on a list of data class instances:
     * the plugin gives the result a generated type argument, which is not a data class.
     * In these cases, use {@get [OF_FUNCTION]}, or [cast][DataFrame.cast] the [DataFrame] to a data class first.
     */
    @ExcludeFromSources
    typealias FromTypeArgument = Nothing

    /**
     * Use this function in most cases.
     * The type argument of this [DataFrame] does not matter,
     * so this function works on a `DataFrame<*>` too,
     * and on a [DataFrame] whose type argument is generated by the compiler plugin.
     */
    @ExcludeFromSources
    typealias FromExplicitType = Nothing
}

// region DataFrame

/**
 * Converts this [DataFrame] into a [List] of [T] instances,
 * where [T] is the type argument of this [DataFrame].
 *
 * @include [CommonToListDocs.FromTypeArgument]
 *
 * @include [CommonToListDocs]
 *
 * ### Example
 * ```kotlin
 * data class Input(val a: Int, val b: Int)
 *
 * val df = dataFrameOf("a", "b")(1, 2, 3, 4)
 *
 * df.cast<Input>().toList() // [Input(a=1, b=2), Input(a=3, b=4)]
 * ```
 *
 * @param [T] The type argument of this [DataFrame]. It has to be a data class.
 * @return A [List] with one [T] instance per row of this [DataFrame].
 * @set [CommonToListDocs.RESULT] list
 * {@set [CommonToListDocs.URL] {@include [DocumentationUrls.ToList]}}
 * @set [CommonToListDocs.OF_FUNCTION] [toListOf][DataFrame.toListOf]
 * @set [CommonToListDocs.SIBLINGS] [toSequence][DataFrame.toSequence] and [toSequenceOf][DataFrame.toSequenceOf] —
 * the same conversion into a [Sequence].
 */
public inline fun <reified T> DataFrame<T>.toList(): List<T> = toSequenceImpl(typeOf<T>()).toList() as List<T>

/**
 * Converts this [DataFrame] into a [List] of [T] instances,
 * where [T] is given explicitly as the type argument of this call.
 *
 * @include [CommonToListDocs.FromExplicitType]
 *
 * @include [CommonToListDocs]
 *
 * ### Example
 * ```kotlin
 * val df = dataFrameOf("name", "lastName", "age")("John", "Doe", 21)
 *     .group("name", "lastName").into("fullName")
 *
 * data class FullName(val name: String, val lastName: String)
 *
 * data class Person(val fullName: FullName, val age: Int)
 *
 * // The "fullName" column group becomes a nested `FullName`
 * df.toListOf<Person>() // [Person(fullName=FullName(name=John, lastName=Doe), age=21)]
 * ```
 *
 * @param [T] The data class to create for each row.
 * @return A [List] with one [T] instance per row of this [DataFrame].
 * @set [CommonToListDocs.RESULT] list
 * {@set [CommonToListDocs.URL] {@include [DocumentationUrls.ToListOf]}}
 * @set [CommonToListDocs.SIBLINGS] [toSequence][DataFrame.toSequence] and [toSequenceOf][DataFrame.toSequenceOf] —
 * the same conversion into a [Sequence].
 */
public inline fun <reified T> DataFrame<*>.toListOf(): List<T> = toSequenceImpl(typeOf<T>()).toList() as List<T>

// endregion
