package org.jetbrains.kotlinx.dataframe.examples.youtube

import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.cast
import org.jetbrains.kotlinx.dataframe.api.convertTo
import org.jetbrains.kotlinx.dataframe.api.generateInterfaces
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.api.schema

/**
 * These data schemas are generated by calling the YouTube API search once.
 * We then call [generateInterfaces] on its schema to generate the Kotlin interfaces.
 *
 * The schema was tweaked manually a bit to include nullability in the right places.
 *
 * Afterward, we can relatively safely [cast] or [convertTo] any search call to [SearchResponse] and
 * the compiler plugin can handle the rest.
 */
fun main() {
    val searchRequest = "example%20search"
    val resultsPerPage = 10
    val maxPages = 5

    val df = load("search?q=$searchRequest&maxResults=$resultsPerPage&part=snippet", maxPages)
    df.schema()
        .generateInterfaces("SearchResponse")
        .print()
}

@DataSchema
interface SearchResponse {
    val etag: String
    val items: List<Items>
    val kind: String
    val nextPageToken: String
    val pageInfo: PageInfo
    val prevPageToken: String?
    val regionCode: String

    @DataSchema(isOpen = false)
    interface Id {
        val kind: String
        val videoId: String?
    }

    @DataSchema(isOpen = false)
    interface Default {
        val height: Int
        val url: String
        val width: Int
    }

    @DataSchema(isOpen = false)
    interface Thumbnails {
        val default: Default
        val high: Default
        val medium: Default
    }

    @DataSchema(isOpen = false)
    interface Snippet {
        val channelId: String
        val channelTitle: String
        val description: String
        val liveBroadcastContent: String
        val publishTime: String
        val publishedAt: String
        val thumbnails: Thumbnails
        val title: String
    }

    @DataSchema(isOpen = false)
    interface Items {
        val etag: String
        val id: Id
        val kind: String
        val snippet: Snippet
    }

    @DataSchema(isOpen = false)
    interface PageInfo {
        val resultsPerPage: Int
        val totalResults: Int
    }
}
