package org.jetbrains.kotlinx.dataframe.examples.json.keyValuePaths

import org.jetbrains.kotlinx.dataframe.DataFrame
import org.jetbrains.kotlinx.dataframe.annotations.ColumnName
import org.jetbrains.kotlinx.dataframe.annotations.DataSchema
import org.jetbrains.kotlinx.dataframe.api.JsonPath
import org.jetbrains.kotlinx.dataframe.api.generateInterfaces
import org.jetbrains.kotlinx.dataframe.api.getFrameColumn
import org.jetbrains.kotlinx.dataframe.api.print
import org.jetbrains.kotlinx.dataframe.api.single
import org.jetbrains.kotlinx.dataframe.io.readJson

/**
 * In this file we'll demonstrate how to use the JSON option `keyValuePaths` when
 * generating data schema interfaces.
 *
 * If you're trying to generate a data schema for JSON files with a very large object,
 * the generated code will be very large and may even cause memory issues.
 * Having a dataframe with thousands of columns is also quite challenging to work with.
 *
 * Since we are just generating data schemas in this file, we only need a sample
 * of our data. However, using the whole file is sometimes more convenient.
 *
 * See also: [our documentation](https://kotlin.github.io/dataframe/read.html#read-from-json).
 */
fun main() {
    noKeyValuePairs()
    withKeyValuePairs()
}

fun noKeyValuePairs() {
    val apiGuruList = object {}::class.java.getResource("/apis_guru_list.json")!!

    val wideDf = DataFrame.readJson(apiGuruList)
    wideDf.print()
    //                                 1forge.com                     1password.com:events                  1password.local:conn...
    // 0 { added:2017-05-30T08:34:14.000Z, pre... { added:2021-07-19T10:17:09.188Z, pre... { added:2021-04-16T15:56:45.939Z, pre...

    wideDf.columnsCount() // 2,361 columns
    wideDf.generateInterfaces()
        .toString()
        .lines()
        .size // 30,341 lines of code would be generated!
}

fun withKeyValuePairs() {
    val apiGuruList = object {}::class.java.getResource("/apis_guru_list.json")!!

    val gatheredDf = DataFrame.readJson(
        url = apiGuruList,
        keyValuePaths = listOf(
            JsonPath(),
            JsonPath().appendWildcard().append("versions"),
        ),
    )
    gatheredDf
        // Since we mark the top-level as key/value path, we'll get a top-level FrameColumn with one row.
        // We might change this: Issue #567
        .getFrameColumn("value").single()
        .print()
    //                                        name                                    value
    //  0                               1forge.com { added:2017-05-30T08:34:14.000Z, pre...
    //  1                     1password.com:events { added:2021-07-19T10:17:09.188Z, pre...
    //  2                  1password.local:connect { added:2021-04-16T15:56:45.939Z, pre...
    //  3            6-dot-authentiqio.appspot.com { added:2017-03-15T14:45:58.000Z, pre...
    //  4                         ably.io:platform { added:2019-07-13T11:28:07.000Z, pre...
    //  5                         ably.net:control { added:2021-07-26T09:45:31.536Z, pre...
    //  6              abstractapi.com:geolocation { added:2021-04-14T17:12:40.648Z, pre...
    //  7                             adafruit.com { added:2018-02-10T10:41:43.000Z, pre...
    // ...

    gatheredDf.generateInterfaces("ApisGuru").print()
}

// auto-generated by withKeyValuePairs()
@Suppress("PropertyName")
@DataSchema
interface ApisGuru {
    val value: List<Value>

    @DataSchema(isOpen = false)
    interface XLogo {
        val url: String
    }

    @DataSchema(isOpen = false)
    interface Info {
        val title: String
        val version: String

        @ColumnName("x-logo")
        val `x-logo`: XLogo

        @ColumnName("x-origin")
        val `x-origin`: List<XLogo>

        @ColumnName("x-providerName")
        val `x-providerName`: String
    }

    @DataSchema(isOpen = false)
    interface Value2 {
        val added: String
        val info: Info
        val openapiVer: String
        val swaggerUrl: String
        val swaggerYamlUrl: String
    }

    @DataSchema(isOpen = false)
    interface Versions {
        val name: String
        val value: Value2
    }

    @DataSchema(isOpen = false)
    interface Value1 {
        val added: String
        val preferred: String
        val versions: List<Versions>
    }

    @DataSchema(isOpen = false)
    interface Value {
        val name: String
        val value: Value1
    }
}
